version: '3.8'

services:
  chore-checklist-app:
    build: .
    ports:
      - "8080:3000"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    volumes:
      # Mount source code for development (optional)
      - ./src:/app/src:ro
